expt_name: Optimised_v10

logging_dir: ./logs/
# checkpoint: False
checkpoint: ./logs/20240906_215442_Optimised_v10/lightning_logs/version_15330562/checkpoints/epoch=48-step=147.ckpt

seed: 42

arch:
  num_conv: 2
  out_channel_conv: [8, 16]
  pooling_kernel_size: 2
  dropout: 0.4

data:
  data_dir: ./data/
  batch_size: 32
  n_mfcc: 25
  max_mfcc_length: 85 # may be calculated as floor(0.5 * sample_rate * window_length / hop_length) + 1
  num_workers: 12

train:
  lr: 0.001
  max_epochs: 100