expt_name: Debugging

do_train: False
do_test: True

logging_dir: ./logs/
checkpoint: ./logs/20240905_215938_Debugging/lightning_logs/version_15267989/checkpoints/epoch=99-step=300.ckpt

seed: 42

data:
  data_dir: ./data/
  batch_size: 32
  n_mfcc: 25
  max_mfcc_length: 85 # may be calculated as floor(0.5 * sample_rate * window_length / hop_length) + 1
  num_workers: 12
train:
  lr: 0.001
  max_epochs: 100