expt_name: Final-8-16

logging_dir: ./logs/
train_checkpoint: False # to resume training from a checkpoint
test_checkpoint: ./logs/20240907_083613_Final-8-16/lightning_logs/version_15330562/checkpoints/epoch=48-step=147.ckpt

analysis:
  ground_truth_file: ./logs/20240907_083613_Final-8-16/y_all.npy
  prediction_file: ./logs/20240907_083613_Final-8-16/y_pred_all.npy

seed: 42

arch:
  out_channels: [8, 16] # for conv layers
  pooling_kernel_size: 2
  dropout: 0.4

data:
  data_dir: ./data/
  batch_size: 32
  n_mfcc: 25
  max_mfcc_length: 85 # may be calculated as floor(0.5 * sample_rate * window_length / hop_length) + 1
  num_workers: 12

train:
  lr: 0.001
  max_epochs: 100