###### For both train.py and test.py ######
seed: 42

data:
  data_dir: ./data/Khan/
  batch_size: 32
  n_mfcc: 25
  max_mfcc_length: 85 # may be calculated as floor(0.5 * sample_rate * window_length / hop_length) + 1
  num_workers: 12

######## For train.py only ########
expt_name: Model-of-Khan
logging_dir: ./logs/
train_checkpoint: False # to resume training from a checkpoint
train:
  lr: 1.0e-5
  max_epochs: 6000

######## For test.py only ########
test_checkpoint:  
test_folder_name: test